-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggVhUAOMdcHa6joLz
U0iK05E0Hh36fYPJgNwyQQryGomgCgYIKoZIzj0DAQehRANCAAQFJY5Q2/8NX5V2
VZdIopib2nBUbtmro97ZbVmHbCvx1CqIQHDi6PCq5qfeTqq/NVYPJqYeWsJrAEY+
/mBoTMyz
-----END PRIVATE KEY-----