CREATE TABLE IF NOT EXISTS `wellness_ticket_issuance` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `center_id` bigint DEFAULT NULL,
    `payment_id` bigint DEFAULT NULL,
    `name` varchar(255) DEFAULT NULL,
    `start_date` datetime(6) DEFAULT NULL,
    `expire_date` datetime(6) DEFAULT NULL,
    `type` varchar(255) DEFAULT NULL,
    `background_color` varchar(10) DEFAULT NULL,
    `text_color` varchar(10) DEFAULT NULL,
    `limit_type` varchar(255) DEFAULT NULL,
    `limit_cnt` int DEFAULT NULL,
    `is_delete` bit(1) DEFAULT FALSE,
    `remaining_cnt` int DEFAULT NULL,
    `total_usable_cnt` int DEFAULT NULL,
    `member_id` bigint DEFAULT NULL,
    `wellness_ticket_id` bigint DEFAULT NULL,
    `is_send_expire_notification` bit(1) DEFAULT NULL,
    `is_send_remaining_cnt_notification` bit(1) DEFAULT NULL,
    `payment_method` enum('IN_APP','ON_SITE') DEFAULT NULL,
    `unpaid_value` int DEFAULT NULL,
    `created_date` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `last_updated_date` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`id`)
  );