CREATE TABLE IF NOT EXISTS mobile_auth_code (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    country_code VARCHAR(10) NOT NULL,
    mobile VARCHAR(20) NOT NULL,
    auth_code VARCHAR(10) NOT NULL,
    expire_date_time DATETIME NOT NULL,
    last_updated_date DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_date DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);