CREATE TABLE IF NOT EXISTS shop_cart (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    member_id BIGINT NOT NULL,
    status ENUM('BEFORE_ORDER', 'COMPLETE_ORDER') NOT NULL,
    last_updated_date DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_date DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);