CREATE TABLE IF NOT EXISTS `member_address` (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  member_id bigint DEFAULT NULL,
  name VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  detail_address VARCHAR(255) NOT NULL,
  recipient VARCHAR(255) NOT NULL,
  mobile VARCHAR(255) NOT NULL,
  zip_code VARCHAR(255) NOT NULL,
  road_name VARCHAR(255) NOT NULL,
  is_default VARCHAR(255) NOT NULL,
  last_updated_date DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  created_date DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
)