ALTER TABLE `reservation` 
MODIFY COLUMN `status` ENUM('INAPP_RESERVATION', 'INAPP_PAYMENT_RESERVATION', 'ADMIN_RESERVATION', 'ONSITE_RESERVATION','MEMBER_CANCELED_RESERVATION','ADMIN_CANCELED_RESERVATION','CHECK_IN', 'ABSENT') DEFAULT NULL;
